name: Build and Publish Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Root Dependencies
        run:  npm install

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend (React)
        working-directory: frontend
        run: CI='' npm run build

      - name: Install Backend Dependencies
        working-directory: backend
        run:  npm install 

      - name: Download binaries (Node, ADB, etc.)
        run: |
          curl -L https://github.com/Harshit-jaat/Automation-Studio/releases/download/v-1.0.0/bin.zip -o bin.zip
          unzip bin.zip -d electron/ || true

      - name: Build and Publish App
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: CI='' npm run build
